FROM prom/prometheus:latest

COPY prometheus.yml /etc/prometheus/prometheus.yml.tmpl

ENTRYPOINT ["/bin/sh", "-c", \
  "sed \"s/\\${HOST_SUFFIX}/${HOST_SUFFIX}/g\" /etc/prometheus/prometheus.yml.tmpl > /tmp/prometheus.yml && \
   exec /bin/prometheus \
     --config.file=/tmp/prometheus.yml \
     --storage.tsdb.path=/prometheus \
     --web.console.libraries=/usr/share/prometheus/console_libraries \
     --web.console.templates=/usr/share/prometheus/consoles"]
