// Temporary stub for generated code
// This would normally be generated by `pnpm run generate-clients`

use solana_pubkey::Pubkey;

// Program ID from the withdraw program
pub const CONTRA_WITHDRAW_PROGRAM_ID: Pubkey = solana_pubkey::pubkey!("J231K9UEpS4y4KAPwGc4gsMNCjKFRMYcQBcjVW7vBhVi");

pub mod errors {
    // Placeholder for generated error types
}

pub mod programs {
    // Placeholder for generated program types
}

pub mod instructions {
    // Placeholder for generated instruction builders
    use solana_instruction::Instruction;
    use solana_pubkey::Pubkey;

    pub struct WithdrawFundsBuilder {
        authority: Option<Pubkey>,
        user_account: Option<Pubkey>,
        destination: Option<Pubkey>,
        amount: Option<u64>,
    }

    impl WithdrawFundsBuilder {
        pub fn new() -> Self {
            Self {
                authority: None,
                user_account: None,
                destination: None,
                amount: None,
            }
        }

        pub fn authority(mut self, authority: Pubkey) -> Self {
            self.authority = Some(authority);
            self
        }

        pub fn user_account(mut self, user_account: Pubkey) -> Self {
            self.user_account = Some(user_account);
            self
        }

        pub fn destination(mut self, destination: Pubkey) -> Self {
            self.destination = Some(destination);
            self
        }

        pub fn amount(mut self, amount: u64) -> Self {
            self.amount = Some(amount);
            self
        }

        pub fn instruction(self) -> Instruction {
            // This is a stub - real implementation would be generated
            Instruction {
                program_id: super::CONTRA_WITHDRAW_PROGRAM_ID,
                accounts: vec![],
                data: vec![],
            }
        }
    }

    impl Default for WithdrawFundsBuilder {
        fn default() -> Self {
            Self::new()
        }
    }
}
