use {
    anyhow::{Context, Result},
    clap::Parser,
    contra_core::client::{
        create_admin_initialize_mint, create_admin_mint_to, create_ata_transaction,
    },
    std::path::PathBuf,
    futures::future::join_all,
    rayon::prelude::*,
    solana_client::nonblocking::rpc_client::RpcClient,
    solana_sdk::{signature::Keypair, signature::Signature, signer::Signer},
    spl_associated_token_account::get_associated_token_address,
    std::{sync::Arc, time::Instant},
    tokio::{sync::RwLock, time::Duration},
    tracing::{info, warn},
};

const MINT_DECIMALS: u8 = 6;

/// How long to wait for all confirmations before giving up.
const CONFIRM_TIMEOUT: Duration = Duration::from_secs(120);
/// How long to sleep between `getSignatureStatuses` polls.
const POLL_INTERVAL: Duration = Duration::from_millis(500);
/// Max concurrent RPC sends per chunk for ATA / mint-to batches.
const MAX_CONCURRENT_SENDS: usize = 64;

#[derive(Parser, Debug)]
#[command(
    name = "contra-bench-tps",
    about = "Load testing binary for the Contra pipeline"
)]
struct Args {
    /// Path to admin keypair JSON file (generated by run.sh)
    #[arg(long, env = "BENCH_ADMIN_KEYPAIR")]
    admin_keypair: PathBuf,

    /// Node RPC endpoint to target
    #[arg(long, default_value = "http://localhost:8899", env = "BENCH_RPC_URL")]
    rpc_url: String,

    /// Number of funded accounts to generate
    #[arg(long, default_value_t = 50, env = "BENCH_ACCOUNTS")]
    accounts: usize,

    /// How long to run the load phase (seconds)
    #[arg(long, default_value_t = 60, env = "BENCH_DURATION")]
    duration: u64,

    /// Number of concurrent sender tasks
    #[arg(long, default_value_t = 10, env = "BENCH_THREADS")]
    threads: usize,

    /// Number of distinct destination accounts (controls sequencer conflict pressure).
    /// Defaults to `--accounts` (no conflicts). Set to 1 for maximum contention.
    #[arg(long, env = "BENCH_NUM_CONFLICT_GROUPS")]
    num_conflict_groups: Option<usize>,

    /// Initial token balance minted to each account
    #[arg(long, default_value_t = 1_000_000, env = "BENCH_INITIAL_BALANCE")]
    initial_balance: u64,

    /// Expose a Prometheus /metrics endpoint on this port (optional)
    #[arg(long, env = "BENCH_METRICS_PORT")]
    metrics_port: Option<u16>,

    /// Log level (error/warn/info/debug/trace)
    #[arg(long, default_value = "info", env = "BENCH_LOG_LEVEL")]
    log_level: String,
}

#[tokio::main]
async fn main() -> Result<()> {
    let args = Args::parse();

    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new(&args.log_level)),
        )
        .init();

    info!(
        rpc_url = %args.rpc_url,
        accounts = args.accounts,
        threads = args.threads,
        duration = args.duration,
        "Starting contra-bench-tps",
    );

    // -------------------------------------------------------------------------
    // Setup phase — task 1: load admin keypair from file
    // -------------------------------------------------------------------------
    let admin_keypair = Arc::new(
        contra_core::client::load_keypair(&args.admin_keypair)
            .map_err(|e| anyhow::anyhow!("failed to load admin keypair: {e}"))?,
    );
    info!(pubkey = %admin_keypair.pubkey(), path = %args.admin_keypair.display(), "Loaded admin keypair");

    // -------------------------------------------------------------------------
    // Setup phase — task 2: generate N account keypairs in parallel
    // -------------------------------------------------------------------------
    let num_conflict_groups = args.num_conflict_groups.unwrap_or(args.accounts);
    let t2 = Instant::now();
    let keypairs: Vec<Arc<Keypair>> = (0..args.accounts)
        .into_par_iter()
        .map(|_| Arc::new(Keypair::new()))
        .collect();
    info!(
        count = keypairs.len(),
        conflict_groups = num_conflict_groups,
        elapsed_ms = t2.elapsed().as_millis(),
        "Generated account keypairs",
    );

    let rpc = RpcClient::new(args.rpc_url.clone());

    // -------------------------------------------------------------------------
    // Setup phase — task 3: create SPL mint (must land before ATAs)
    //
    // Use send_transaction + poll_confirmations instead of
    // send_and_confirm_transaction: the contra node settles asynchronously
    // through its pipeline so the solana-client's built-in confirmation
    // timeout (tied to blockhash expiry) fires before settlement completes.
    //
    // Retry the send with backoff in case the write-node is still warming up.
    // -------------------------------------------------------------------------
    let t3 = Instant::now();
    let mint_keypair = Keypair::new();
    let mint = mint_keypair.pubkey();
    let send_retry_delays: &[u64] = &[1, 2, 4, 8, 16, 30];
    let mint_sig = 'send: {
        let mut last_err = String::new();
        for (attempt, &delay_secs) in send_retry_delays.iter().enumerate() {
            match rpc.get_latest_blockhash().await {
                Err(e) => {
                    warn!(attempt, err = %e, "get_latest_blockhash failed, retrying in {delay_secs}s");
                    last_err = e.to_string();
                }
                Ok(blockhash) => {
                    let init_tx =
                        create_admin_initialize_mint(&admin_keypair, &mint, MINT_DECIMALS, blockhash);
                    match rpc.send_transaction(&init_tx).await {
                        Ok(sig) => break 'send sig,
                        Err(e) => {
                            warn!(attempt, err = %e, "initialize_mint send failed, retrying in {delay_secs}s");
                            last_err = e.to_string();
                        }
                    }
                }
            }
            tokio::time::sleep(Duration::from_secs(delay_secs)).await;
        }
        return Err(anyhow::anyhow!("initialize_mint: all retries exhausted: {last_err}"));
    };
    poll_confirmations(&rpc, &[mint_sig], "initialize_mint").await?;
    info!(
        mint = %mint,
        elapsed_ms = t3.elapsed().as_millis(),
        "Mint initialized",
    );

    // -------------------------------------------------------------------------
    // Setup phase — task 4: create ATAs for all keypairs in parallel
    // -------------------------------------------------------------------------
    let t4 = Instant::now();
    let blockhash = rpc.get_latest_blockhash().await.context("get_latest_blockhash")?;
    let ata_sigs = send_parallel(&args.rpc_url, &keypairs, |kp, url| {
        let admin = Arc::clone(&admin_keypair);
        let owner = kp.pubkey();
        async move {
            let tx = create_ata_transaction(&admin, &owner, &mint, blockhash);
            RpcClient::new(url).send_transaction(&tx).await
        }
    })
    .await;
    info!(
        sent = ata_sigs.len(),
        total = keypairs.len(),
        elapsed_ms = t4.elapsed().as_millis(),
        "ATA transactions sent",
    );

    // -------------------------------------------------------------------------
    // Setup phase — task 5: poll until all ATAs are confirmed
    // -------------------------------------------------------------------------
    let t5 = Instant::now();
    poll_confirmations(&rpc, &ata_sigs, "ATA").await?;
    info!(
        confirmed = ata_sigs.len(),
        elapsed_ms = t5.elapsed().as_millis(),
        "ATAs confirmed",
    );

    // -------------------------------------------------------------------------
    // Setup phase — task 6: mint tokens to all ATAs in parallel
    // -------------------------------------------------------------------------
    let t6 = Instant::now();
    let blockhash = rpc.get_latest_blockhash().await.context("get_latest_blockhash")?;
    let mint_sigs = send_parallel(&args.rpc_url, &keypairs, |kp, url| {
        let admin = Arc::clone(&admin_keypair);
        let ata = get_associated_token_address(&kp.pubkey(), &mint);
        async move {
            let tx = create_admin_mint_to(&admin, &mint, &ata, args.initial_balance, blockhash);
            RpcClient::new(url).send_transaction(&tx).await
        }
    })
    .await;
    info!(
        sent = mint_sigs.len(),
        total = keypairs.len(),
        elapsed_ms = t6.elapsed().as_millis(),
        "Mint-to transactions sent",
    );

    // -------------------------------------------------------------------------
    // Setup phase — task 7: poll until all mint-to are confirmed
    // -------------------------------------------------------------------------
    let t7 = Instant::now();
    poll_confirmations(&rpc, &mint_sigs, "mint-to").await?;
    info!(
        confirmed = mint_sigs.len(),
        elapsed_ms = t7.elapsed().as_millis(),
        "Mint-to confirmed",
    );

    // -------------------------------------------------------------------------
    // Setup phase — task 8: fetch initial blockhash, seed shared state
    // -------------------------------------------------------------------------
    let t8 = Instant::now();
    let initial_blockhash = rpc.get_latest_blockhash().await.context("get_latest_blockhash")?;
    let _current_blockhash = Arc::new(RwLock::new(initial_blockhash));
    info!(
        blockhash = %initial_blockhash,
        elapsed_ms = t8.elapsed().as_millis(),
        "Initial blockhash seeded — setup complete",
    );

    Ok(())
}

/// Send one transaction per keypair concurrently (in chunks of MAX_CONCURRENT_SENDS).
/// Returns all successful signatures; logs and discards failures.
async fn send_parallel<F, Fut>(
    rpc_url: &str,
    keypairs: &[Arc<Keypair>],
    build: F,
) -> Vec<Signature>
where
    F: Fn(&Arc<Keypair>, String) -> Fut,
    Fut: std::future::Future<Output = Result<Signature, solana_client::client_error::ClientError>>,
{
    let mut sigs = Vec::with_capacity(keypairs.len());

    for chunk in keypairs.chunks(MAX_CONCURRENT_SENDS) {
        let futures: Vec<_> = chunk
            .iter()
            .map(|kp| build(kp, rpc_url.to_owned()))
            .collect();
        for res in join_all(futures).await {
            match res {
                Ok(sig) => sigs.push(sig),
                Err(e) => warn!(err = %e, "send failed"),
            }
        }
    }

    sigs
}

/// Poll `getSignatureStatuses` until every signature is either confirmed or
/// failed, or until CONFIRM_TIMEOUT elapses.
async fn poll_confirmations(rpc: &RpcClient, sigs: &[Signature], label: &str) -> Result<()> {
    if sigs.is_empty() {
        return Ok(());
    }

    let deadline = tokio::time::Instant::now() + CONFIRM_TIMEOUT;

    loop {
        let statuses = rpc
            .get_signature_statuses(sigs)
            .await
            .context("get_signature_statuses")?
            .value;

        let confirmed = statuses
            .iter()
            .filter(|s| s.as_ref().map_or(false, |s| s.err.is_none()))
            .count();
        let failed = statuses
            .iter()
            .filter(|s| s.as_ref().map_or(false, |s| s.err.is_some()))
            .count();
        let pending = sigs.len() - confirmed - failed;

        info!(label, confirmed, failed, pending, "Polling confirmations");

        if pending == 0 {
            if failed > 0 {
                warn!(label, failed, "Some transactions failed during confirmation");
            }
            return Ok(());
        }

        if tokio::time::Instant::now() >= deadline {
            return Err(anyhow::anyhow!(
                "Timeout waiting for {label} confirmations: {confirmed}/{} confirmed, {failed} failed",
                sigs.len()
            ));
        }

        tokio::time::sleep(POLL_INTERVAL).await;
    }
}
